services:
  directory-lister:
    image: directorylister/directorylister:5
    environment:
      CACHE_DRIVER: redis
      REDIS_HOST: cache
      REDIS_PORT: 6379
    ports:
      - 4981:80
    volumes:
      - ./data:/data
    depends_on: [cache]
    restart: unless-stopped

  cache:
    image: valkey/valkey:8-bookworm
    restart: unless-stopped