services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./.env:/var/www/html/DirectoryLister/.env

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./.env:/var/www/html/DirectoryLister/.env
    depends_on:
      - app
    ports:
      - "4981:8080"