version: '3.9'
services:
  directorylister:
    build:
      context: ./docker
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./files:/var/www/html/
      - ./config/.env:/var/www/html/.env
    ports:
      - "4981:8080"
