services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./.env:/var/www/html/DirectoryLister/.env
    ports:
      - "4981:8080"
  nginx:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./.env:/var/www/html/DirectoryLister/.env

