services:
  directorylister:
    build:
      context: ./docker
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./docker/config/.env:/var/www/html/.env
    ports:
      - "4981:8080"
